language: php

php:
  - 5.5
  - 5.6
  - 7.0
  - hhvm

matrix:
  allow_failures:
    - php: hhvm
  include:
    - php: 5.6
      env: SYMFONY_VERSION="2.5.*"
    - php: 5.6
      env: SYMFONY_VERSION="2.6.*"
    - php: 5.6
      env: SYMFONY_VERSION="2.7.*"
    - php: 5.6
      env: SYMFONY_VERSION="2.8.*"
    - php: 7.0
      env: SYMFONY_VERSION="2.8.*"

before_install:
  - composer self-update
  - if [ "$SYMFONY_VERSION" != "" ]; then composer require --no-update symfony/framework-bundle:$SYMFONY_VERSION  symfony/console:$SYMFONY_VERSION symfony/dependency-injection:$SYMFONY_VERSION symfony/http-kernel:$SYMFONY_VERSION symfony/config:$SYMFONY_VERSION; fi

install:
  - composer update --prefer-dist

script:
  - vendor/bin/phpunit --coverage-clover build/logs/clover.xml
  - vendor/bin/behat

after_script:
  - vendor/bin/coveralls
